XTENSION= 'BINTABLE'           / FITS Binary Table Extension
BITPIX  =                    8 /
NAXIS   =                    2 /
NAXIS1  =                  112 /
NAXIS2  =                 1058 /
PCOUNT  =                    0 /
GCOUNT  =                    1 /
TFIELDS =                   10 /
EXTNAME = 'FLAG    '           /
EXTVER  =                    1 /
TTYPE1  = 'SOURCE_ID'          / source id number from source tbl
TFORM1  = '1J      '           /
TTYPE2  = 'ARRAY   '           / ????
TFORM2  = '1J      '           /
TTYPE3  = 'ANTS    '           / antenna id from antennas tbl
TFORM3  = '2J      '           /
TUNIT3  = '        '           /
TTYPE4  = 'FREQID  '           / freq id number from frequency tbl
TFORM4  = '1J      '           /
TTYPE5  = 'TIMERANG'           / time flag condition begins, ends
TFORM5  = '2E      '           /
TUNIT5  = 'DAYS    '           /
TTYPE6  = 'BANDS   '           / true if the baseband is bad
TFORM6  = '4J      '           /
TTYPE7  = 'CHANS   '           / channel range to be flagged
TFORM7  = '2J      '           /
TTYPE8  = 'PFLAGS  '           / flag array for polarization
TFORM8  = '4J      '           /
TTYPE9  = 'REASON  '           / reason for data to be flagged bad
TFORM9  = '40A     '           /
TTYPE10 = 'SEVERITY'           / severity code
TFORM10 = '1J      '           /
OBSCODE = 'BL146   '           / Proposal code
RDATE   = '2007-08-23'         / Reference date
NO_STKD =                    4 / Nmbr stokes
STK_1   =                   -1 / First stokes
NO_BAND =                    4 / Number of basebands
NO_CHAN =                    8 / Number of channels
REF_FREQ=   8.40549000000000000E+09 / Frequency reference
CHAN_BW =   1.00000000000000000E+06 / Channel bandwidth
REF_PIXL=   5.31250000000000000E-01 /
TABREV  =                    2 /
END