XTENSION= 'BINTABLE'           / FITS Binary Table Extension
BITPIX  =                    8 /
NAXIS   =                    2 /
NAXIS1  =                  64  / Num bytes in row
NAXIS2  =                    1 / Num rows
PCOUNT  =                    0 /
GCOUNT  =                    1 /
TFIELDS =                    6 / Num cols
EXTNAME = 'FREQUENCY'          /
EXTVER  =                    1 /
TTYPE1  = 'FREQID  '           / FREQID number in uv data
TFORM1  = '1J      '           /
TTYPE2  = 'BANDFREQ'           / frequency offset
TFORM2  = '4D      '           /
TUNIT2  = 'HZ      '           /
TTYPE3  = 'CH_WIDTH'           / spectral channel bandwidth
TFORM3  = '4E      '           /
TUNIT3  = 'HZ      '           /
TTYPE4  = 'TOTAL_BANDWIDTH'    / total bw of a BAND
TFORM4  = '4E      '           /
TUNIT4  = 'HZ      '           /
TTYPE5  = 'SIDEBAND'           / sideband of each BAND
TFORM5  = '4J      '           /
TTYPE6  = 'BB_CHAN '           / baseband channel number (1-16)
TFORM6  = '4J      '           /
OBSCODE = 'BL146   '           /
RDATE   = '2007-08-23'         /
NO_STKD =                    4 /
STK_1   =                   -1 /
NO_BAND =                    4 /
NO_CHAN =                    8 /
REF_FREQ=   8.40549000000000000E+09 /
CHAN_BW =   1.00000000000000000E+06 /
REF_PIXL=   5.31250000000000000E-01 /
TABREV  =                    2 /
END