XTENSION= 'BINTABLE'           / FITS Binary Table Extension
BITPIX  =                    8 /
NAXIS   =                    2 /
NAXIS1  =                  588 /
NAXIS2  =                   10 /
PCOUNT  =                    0 /
GCOUNT  =                    1 /
TFIELDS =                   19 /
EXTNAME = 'GAIN_CURVE'         /
EXTVER  =                    1 /
TTYPE1  = 'ANTENNA_NO'         / antenna id from array geom. tbl
TFORM1  = '1J      '           /
TUNIT1  = '        '           /
TTYPE2  = 'ARRAY   '           / ????
TFORM2  = '1J      '           /
TTYPE3  = 'FREQID  '           / freq id number from frequency tbl
TFORM3  = '1J      '           /
TUNIT3  = '        '           /
TTYPE4  = 'TYPE_1  '           / gain curve type
TFORM4  = '4J      '           /
TUNIT4  = '        '           /
TTYPE5  = 'NTERM_1 '           / number of terms
TFORM5  = '4J      '           /
TUNIT5  = '        '           /
TTYPE6  = 'X_TYP_1 '           / abscissa type of plot
TFORM6  = '4J      '           /
TUNIT6  = '        '           /
TTYPE7  = 'Y_TYP_1 '           / second axis of 3d plot
TFORM7  = '4J      '           /
TUNIT7  = '        '           /
TTYPE8  = 'X_VAL_1 '           / For tabulated curves
TFORM8  = '4E      '           /
TUNIT8  = '        '           /
TTYPE9  = 'Y_VAL_1 '           / For tabulated curves
TFORM9  = '24E     '           /
TUNIT9  = '        '           /
TTYPE10 = 'GAIN_1  '           / Gain curve
TFORM10 = '24E     '           /
TUNIT10 = '        '           /
TTYPE11 = 'SENS_1  '           / Sensitivity
TFORM11 = '4E      '           /
TUNIT11 = 'Kelvin/Jy'          /
TTYPE12 = 'TYPE_2  '           / gain curve type
TFORM12 = '4J      '           /
TUNIT12 = '        '           /
TTYPE13 = 'NTERM_2 '           / number of terms
TFORM13 = '4J      '           /
TUNIT13 = '        '           /
TTYPE14 = 'X_TYP_2 '           / abscissa type of plot
TFORM14 = '4J      '           /
TUNIT14 = '        '           /
TTYPE15 = 'Y_TYP_2 '           / second axis of 3d plot
TFORM15 = '4J      '           /
TUNIT15 = '        '           /
TTYPE16 = 'X_VAL_2 '           / For tabulated curves
TFORM16 = '4E      '           /
TUNIT16 = '        '           /
TTYPE17 = 'Y_VAL_2 '           / For tabulated curves
TFORM17 = '24E     '           /
TUNIT17 = '        '           /
TTYPE18 = 'GAIN_2  '           / Gain curve
TFORM18 = '24E     '           /
TUNIT18 = '        '           /
TTYPE19 = 'SENS_2  '           / Sensitivity
TFORM19 = '4E      '           /
TUNIT19 = 'Kelvin/Jy'          /
OBSCODE = 'BL146   '           / Proposal code
RDATE   = '2007-08-23'         / Reference date
NO_STKD =                    4 / Nmbr stokes
STK_1   =                   -1 / First stokes
NO_BAND =                    4 / Number of basebands
NO_CHAN =                    8 / Number of channels
REF_FREQ=   8.40549000000000000E+09 / Frequency reference
CHAN_BW =   1.00000000000000000E+06 / Channel bandwidth
REF_PIXL=   5.31250000000000000E-01 /
NO_POL  =                    2 /
NO_TABS =                    6 /
TABREV  =                    1 /
END