XTENSION= 'BINTABLE'           / FITS Binary Table Extension
BITPIX  =                    8 /
NAXIS   =                    2 /
NAXIS1  =                 1024 /
NAXIS2  =                  640 /
PCOUNT  =                    0 /
GCOUNT  =                    1 /
TFIELDS =                   20 /
EXTNAME = 'INTERFEROMETER_MODEL' /
EXTVER  =                    1 /
TTYPE1  = 'TIME    '           / time of model start
TFORM1  = '1D      '           /
TUNIT1  = 'DAYS    '           /
TTYPE2  = 'TIME_INTERVAL'      / model interval
TFORM2  = '1E      '           /
TUNIT2  = 'DAYS    '           /
TTYPE3  = 'SOURCE_ID'          / source id from sources tbl
TFORM3  = '1J      '           /
TTYPE4  = 'ANTENNA_NO'         / antenna number from antennas tbl
TFORM4  = '1J      '           /
TTYPE5  = 'ARRAY   '           / array id number
TFORM5  = '1J      '           /
TTYPE6  = 'FREQID  '           / frequency id number from frequency tbl
TFORM6  = '1J      '           /
TTYPE7  = 'I.FAR.ROT'          / ionospheric faraday rotation
TFORM7  = '1E      '           /
TUNIT7  = 'RAD/METER**2'       /
TTYPE8  = 'FREQ.VAR'           / time variable freq. offset
TFORM8  = '4E      '           /
TUNIT8  = 'HZ      '           /
TTYPE9  = 'PDELAY_1'           / total phase delay at ref time
TFORM9  = '24D     '           /
TUNIT9  = 'TURNS   '           /
TTYPE10 = 'GDELAY_1'           / total group delay at ref time
TFORM10 = '6D      '           /
TUNIT10 = 'SECONDS '           /
TTYPE11 = 'PRATE_1 '           / phase delay rate
TFORM11 = '24D     '           /
TUNIT11 = 'HZ      '           /
TTYPE12 = 'GRATE_1 '           / group delay rate
TFORM12 = '6D      '           /
TUNIT12 = 'SEC/SEC '           /
TTYPE13 = 'DISP_1  '           / dispersive delay for polar.1
TFORM13 = '1E      '           /
TUNIT13 = 'SECONDS '           /
TTYPE14 = 'DDISP_1 '           / dispersive delay rate for polar. 1
TFORM14 = '1E      '           /
TUNIT14 = 'SEC/SEC '           /
TTYPE15 = 'PDELAY_2'           / total phase delay at ref time
TFORM15 = '24D     '           /
TUNIT15 = 'TURNS   '           /
TTYPE16 = 'GDELAY_2'           / total group delay at ref time
TFORM16 = '6D      '           /
TUNIT16 = 'SECONDS '           /
TTYPE17 = 'PRATE_2 '           / phase delay rate
TFORM17 = '24D     '           /
TUNIT17 = 'HZ      '           /
TTYPE18 = 'GRATE_2 '           / group delay rate
TFORM18 = '6D      '           /
TUNIT18 = 'SEC/SEC '           /
TTYPE19 = 'DISP_2  '           / dispersive delay for polar.2
TFORM19 = '1E      '           /
TUNIT19 = 'SECONDS '           /
TTYPE20 = 'DDISP_2 '           / dispersive delay rate for polar. 2
TFORM20 = '1E      '           /
TUNIT20 = 'SEC/SEC '           /
OBSCODE = 'BL146   '           /
RDATE   = '2007-08-23'         /
NO_STKD =                    4 /
STK_1   =                   -1 /
NO_BAND =                    4 /
NO_CHAN =                    8 /
REF_FREQ=   8.40549000000000000E+09 /
CHAN_BW =   1.00000000000000000E+06 /
REF_PIXL=   5.31250000000000000E-01 /
TABREV  =                    2 /
NO_POL  =                    2 /
GSTIA0  =   0.00000000000000000E+00 /
DEGPDY  =   0.00000000000000000E+00 /
RDATE   = '2007-08-23'         /
CDATE   = '2007-08-31'         /
NPOLY   =                    6 /
REVISION=   1.00000000000000000E+00 /
END