XTENSION= 'BINTABLE'           / FITS Binary Table Extension
BITPIX  =                    8 /
NAXIS   =                    2 /
NAXIS1  =                  168 /
NAXIS2  =                 1060 /
PCOUNT  =                    0 /
GCOUNT  =                    1 /
TFIELDS =                   21 /
EXTNAME = 'MODEL_COMPS'        /
EXTVER  =                    1 /
TTYPE1  = 'TIME    '           / Time of center of interval
TFORM1  = '1D      '           /
TUNIT1  = 'DAYS    '           /
TTYPE2  = 'SOURCE_ID'          / source id from sources tbl
TFORM2  = '1J      '           /
TTYPE3  = 'ANTENNA_NO'         / antenna id from antennas tbl
TFORM3  = '1J      '           /
TTYPE4  = 'ARRAY   '           / array id number
TFORM4  = '1J      '           /
TTYPE5  = 'FREQID  '           / freq id from frequency tbl
TFORM5  = '1J      '           /
TTYPE6  = 'ATMOS   '           / atmospheric group delay
TFORM6  = '1D      '           /
TUNIT6  = 'SECONDS '           /
TTYPE7  = 'DATMOS  '           / atmospheric group delay rate
TFORM7  = '1D      '           /
TUNIT7  = 'SEC/SEC '           /
TTYPE8  = 'GDELAY  '           / CALC geometric delay
TFORM8  = '1D      '           /
TUNIT8  = 'SECONDS '           /
TTYPE9  = 'GRATE   '           / CALC geometric delay rate
TFORM9  = '1D      '           /
TUNIT9  = 'SEC/SEC '           /
TTYPE10 = 'CLOCK_1 '           / electronic delay
TFORM10 = '1D      '           /
TUNIT10 = 'SECONDS '           /
TTYPE11 = 'DCLOCK_1'           / electronic delay rate
TFORM11 = '1D      '           /
TUNIT11 = 'SEC/SEC '           /
TTYPE12 = 'LO_OFFSET_1'        / station lo_offset for polar. 1
TFORM12 = '4E      '           /
TUNIT12 = 'HZ      '           /
TTYPE13 = 'DLO_OFFSET_1'       / station lo_offset rate for polar. 1
TFORM13 = '4E      '           /
TUNIT13 = 'HZ/SEC  '           /
TTYPE14 = 'DISP_1  '           / dispersive delay
TFORM14 = '1E      '           /
TUNIT14 = 'SECONDS '           /
TTYPE15 = 'DDISP_1 '           / dispersive delay rate
TFORM15 = '1E      '           /
TUNIT15 = 'SEC/SEC '           /
TTYPE16 = 'CLOCK_2 '           / electronic delay
TFORM16 = '1D      '           /
TUNIT16 = 'SECONDS '           /
TTYPE17 = 'DCLOCK_2'           / electronic delay rate
TFORM17 = '1D      '           /
TUNIT17 = 'SEC/SEC '           /
TTYPE18 = 'LO_OFFSET_2'        / station lo_offset for polar. 2
TFORM18 = '4E      '           /
TUNIT18 = 'HZ      '           /
TTYPE19 = 'DLO_OFFSET_2'       / station lo_offset rate for polar. 2
TFORM19 = '4E      '           /
TUNIT19 = 'HZ/SEC  '           /
TTYPE20 = 'DISP_2  '           / dispersive delay for polar 2
TFORM20 = '1E      '           /
TUNIT20 = 'SECONDS '           /
TTYPE21 = 'DDISP_2 '           / dispersive delay rate for polar 2
TFORM21 = '1E      '           /
TUNIT21 = 'SEC/SEC '           /
OBSCODE = 'BL146   '           /
RDATE   = '2007-08-23'         /
NO_STKD =                    4 /
STK_1   =                   -1 /
NO_BAND =                    4 /
NO_CHAN =                    8 /
REF_FREQ=   8.40549000000000000E+09 /
CHAN_BW =   1.00000000000000000E+06 /
REF_PIXL=   5.31250000000000000E-01 /
NO_POL  =                    2 /
FFT_SIZE=                  256 /
OVERSAMP=                    0 /
ZERO_PAD=                    0 /
FFT_TWID=                    1 / Version of FFT twiddle table used
TAPER_FN= 'UNIFORM '           /
TABREV  =                    1 /
END