XTENSION= 'BINTABLE'           / FITS Binary Table Extension
BITPIX  =                    8 /
NAXIS   =                    2 /
NAXIS1  =                  484 /
NAXIS2  =                  241 /
PCOUNT  =                    0 /
GCOUNT  =                    1 /
TFIELDS =                   17 /
EXTNAME = 'PHASE-CAL'          /
EXTVER  =                    1 /
TTYPE1  = 'TIME    '           / time of center of interval
TFORM1  = '1D      '           /
TUNIT1  = 'DAYS    '           /
TTYPE2  = 'TIME_INTERVAL'      / time span of datum
TFORM2  = '1E      '           /
TUNIT2  = 'DAYS    '           /
TTYPE3  = 'SOURCE_ID'          / source id number from source tbl
TFORM3  = '1J      '           /
TTYPE4  = 'ANTENNA_NO'         / antenna id from array geom. tbl
TFORM4  = '1J      '           /
TTYPE5  = 'ARRAY   '           / ????
TFORM5  = '1J      '           /
TTYPE6  = 'FREQID  '           / freq id number from frequency tbl
TFORM6  = '1J      '           /
TTYPE7  = 'CABLE_CAL'          / cable length calibration
TFORM7  = '1D      '           /
TUNIT7  = 'SECONDS '           /
TTYPE8  = 'STATE_1 '           / state counts (4 per baseband)
TFORM8  = '16E     '           /
TTYPE9  = 'PC_FREQ_1'          / Pcal recorded frequency
TFORM9  = '8D      '           /
TUNIT9  = 'Hz      '           /
TTYPE10 = 'PC_REAL_1'          / Pcal real
TFORM10 = '8E      '           /
TTYPE11 = 'PC_IMAG_1'          / Pcal imag
TFORM11 = '8E      '           /
TTYPE12 = 'PC_RATE_1'          / Pcal rate
TFORM12 = '8E      '           /
TTYPE13 = 'STATE_2 '           / state counts (4 per baseband)
TFORM13 = '16E     '           /
TTYPE14 = 'PC_FREQ_2'          / Pcal recorded frequency
TFORM14 = '8D      '           /
TUNIT14 = 'Hz      '           /
TTYPE15 = 'PC_REAL_2'          / Pcal real
TFORM15 = '8E      '           /
TTYPE16 = 'PC_IMAG_2'          / Pcal imag
TFORM16 = '8E      '           /
TTYPE17 = 'PC_RATE_2'          / Pcal rate
TFORM17 = '8E      '           /
OBSCODE = 'BL146   '           / Proposal code
RDATE   = '2007-08-23'         / Reference date
NO_STKD =                    4 / Nmbr stokes
STK_1   =                   -1 / First stokes
NO_BAND =                    4 / Number of basebands
NO_CHAN =                    8 / Number of channels
REF_FREQ=   8.40549000000000000E+09 / Frequency reference
CHAN_BW =   1.00000000000000000E+06 / Channel bandwidth
REF_PIXL=   5.31250000000000000E-01 /
NO_TONES=                    2 /
NO_POL  =                    2 /
TABREV  =                    2 /
END