XTENSION= 'BINTABLE'           / FITS Binary Table Extension
BITPIX  =                    8 /
NAXIS   =                    2 /
NAXIS1  =                  128 /
NAXIS2  =                    6 /
PCOUNT  =                    0 /
GCOUNT  =                    1 /
TFIELDS =                   23 /
EXTNAME = 'SOURCE  '           /
EXTVER  =                    1 /
TTYPE1  = 'ID_NO.  '           / source id number
TFORM1  = '1J      '           /
TTYPE2  = 'SOURCE  '           / source name
TFORM2  = '16A     '           /
TTYPE3  = 'QUAL    '           / source qualifier
TFORM3  = '1J      '           /
TTYPE4  = 'CALCODE '           / calibrator code
TFORM4  = '4A      '           /
TTYPE5  = 'FREQID  '           / freq id number in frequency tbl
TFORM5  = '1J      '           /
TTYPE6  = 'IFLUX   '           / ipol flux density at ref freq
TFORM6  = '4E      '           /
TUNIT6  = 'JY      '           /
TTYPE7  = 'QFLUX   '           / qpol flux density at ref freq
TFORM7  = '4E      '           /
TUNIT7  = 'JY      '           /
TTYPE8  = 'UFLUX   '           / upol flux density at ref freq
TFORM8  = '4E      '           /
TUNIT8  = 'JY      '           /
TTYPE9  = 'VFLUX   '           / vpol flux density at ref freq
TFORM9  = '4E      '           /
TUNIT9  = 'JY      '           /
TTYPE10 = 'ALPHA   '           / spectral index
TFORM10 = '4E      '           /
TTYPE11 = 'FREQOFF '           / freq. offset from ref freq.
TFORM11 = '4D      '           /
TUNIT11 = 'HZ      '           /
TTYPE12 = 'RAEPO   '           / Right Ascension at EPOCH
TFORM12 = '1D      '           /
TUNIT12 = 'DEGREES '           /
TTYPE13 = 'DECEPO  '           / Declination at EPOCH
TFORM13 = '1D      '           /
TUNIT13 = 'DEGREES '           /
TTYPE14 = 'EPOCH   '           / epoch 1950.0B or J2000
TFORM14 = '1D      '           /
TUNIT14 = 'YEARS   '           /
TTYPE15 = 'RAAPP   '           / apparent RA at 0 IAT ref day
TFORM15 = '1D      '           /
TUNIT15 = 'DEGREES '           /
TTYPE16 = 'DECAPP  '           / apparent Dec at 0 IAT ref day
TFORM16 = '1D      '           /
TUNIT16 = 'DEGREES '           /
TTYPE17 = 'SYSVEL  '           / systemic velocity at ref pixal
TFORM17 = '4D      '           /
TUNIT17 = 'M/SEC   '           /
TTYPE18 = 'VELTYP  '           / velocity type
TFORM18 = '8A      '           /
TTYPE19 = 'VELDEF  '           / velocity def: radio, optical
TFORM19 = '8A      '           /
TTYPE20 = 'RESTFREQ'           / line rest frequency
TFORM20 = '4D      '           /
TUNIT20 = 'HZ      '           /
TTYPE21 = 'PMRA    '           / proper motion in RA
TFORM21 = '1D      '           /
TUNIT21 = 'DEG/DAY '           /
TTYPE22 = 'PMDEC   '           / proper motion in Dec
TFORM22 = '1D      '           /
TUNIT22 = 'DEG/DAY '           /
TTYPE23 = 'PARALLAX'           / parallax of source
TFORM23 = '1E      '           /
TUNIT23 = 'ARCSEC  '           /
OBSCODE = 'BL146   '           /
RDATE   = '2007-08-23'         /
NO_STKD =                    4 /
STK_1   =                   -1 /
NO_BAND =                    4 /
NO_CHAN =                    8 /
REF_FREQ=   8.40549000000000000E+09 /
CHAN_BW =   1.00000000000000000E+06 /
REF_PIXL=   5.31250000000000000E-01 /
TABREV  =                    1 /
END