XTENSION= 'BINTABLE'           / FITS Binary Table Extension
BITPIX  =                    8 /
NAXIS   =                    2 /
NAXIS1  =                   72 /
NAXIS2  =                    0 / [number of rows is initially zero]
PCOUNT  =                    0 /
GCOUNT  =                    1 /
TFIELDS =                    4 /
EXTNAME = 'SPACECRAFT_ORBIT'   /
EXTVER  =                    1 /
TTYPE1  = 'SPACECR '           / spacecraft name
TFORM1  = '16A     '           /
TTYPE2  = 'TIME    '           / UT time
TFORM2  = '1D      '           /
TUNIT2  = 'DAYS    '           /
TTYPE3  = 'ORBXYZ  '           / geocentric coordinates
TFORM3  = '3D      '           /
TUNIT3  = 'METERS  '           /
TTYPE4  = 'VELXYZ  '           / velcity vector
TFORM4  = '3D      '           /
TUNIT4  = 'METERS/SEC'         /
OBSCODE = 'BL146   '           /
RDATE   = '2007-08-23'         /
NO_STKD =                    4 /
STK_1   =                   -1 /
NO_BAND =                    4 /
NO_CHAN =                    8 /
REF_FREQ=   8.40549000000000000E+09 /
CHAN_BW =   1.00000000000000000E+06 /
REF_PIXL=   5.31250000000000000E-01 /
TABREV  =                    1 /
END