XTENSION= 'BINTABLE'           / FITS Binary Table Extension
BITPIX  =                    8 /
NAXIS   =                    2 /
NAXIS1  =                   92 /
NAXIS2  =                  398 /
PCOUNT  =                    0 /
GCOUNT  =                    1 /
TFIELDS =                   10 /
EXTNAME = 'SYSTEM_TEMPERATURE' /
EXTVER  =                    1 /
TTYPE1  = 'TIME    '           / time of center of interval
TFORM1  = '1D      '           /
TUNIT1  = 'DAYS    '           /
TTYPE2  = 'TIME_INTERVAL'      / time span of datum
TFORM2  = '1E      '           /
TUNIT2  = 'DAYS    '           /
TTYPE3  = 'SOURCE_ID'          / source id number from source tbl
TFORM3  = '1J      '           /
TTYPE4  = 'ANTENNA_NO'         / antenna id from array geom. tbl
TFORM4  = '1J      '           /
TTYPE5  = 'ARRAY   '           / ????
TFORM5  = '1J      '           /
TTYPE6  = 'FREQID  '           / freq id number from frequency tbl
TFORM6  = '1J      '           /
TTYPE7  = 'TSYS_1  '           / system temperature
TFORM7  = '4E      '           /
TUNIT7  = 'K       '           /
TTYPE8  = 'TANT_1  '           / antenna temperature
TFORM8  = '4E      '           /
TUNIT8  = 'K       '           /
TTYPE9  = 'TSYS_2  '           / system temperature
TFORM9  = '4E      '           /
TUNIT9  = 'K       '           /
TTYPE10 = 'TANT_2  '           / antenna temperature
TFORM10 = '4E      '           /
TUNIT10 = 'K       '           /
OBSCODE = 'BL146   '           / Proposal code
RDATE   = '2007-08-23'         / Reference date
NO_STKD =                    4 / Nmbr stokes
STK_1   =                   -1 / First stokes
NO_BAND =                    4 / Number of basebands
NO_CHAN =                    8 / Number of channels
REF_FREQ=   8.40549000000000000E+09 / Frequency reference
CHAN_BW =   1.00000000000000000E+06 / Channel bandwidth
REF_PIXL=   5.31250000000000000E-01 /
NO_POL  =                    2 /
TABREV  =                    1 /
END