XTENSION= 'BINTABLE'           / FITS Binary Table Extension
BITPIX  =                    8 /
NAXIS   =                    2 /
NAXIS1  =                   72 /
NAXIS2  =                90240 /
PCOUNT  =                    0 /
GCOUNT  =                    1 /
TFIELDS =                   15 /
EXTNAME = 'TAPE_STATISTICS'    /
EXTVER  =                    1 /
TTYPE1  = 'TIME    '           / time of center of interval
TFORM1  = '1D      '           /
TUNIT1  = 'DAYS    '           /
TTYPE2  = 'VSN     '           / VSN id
TFORM2  = '8A      '           /
TTYPE3  = 'ANTENNA_NO'         / antenna id from antennas tbl
TFORM3  = '1J      '           /
TTYPE4  = 'ANTENNA_NAME'       / antenna name
TFORM4  = '4A      '           /
TTYPE5  = 'REC_NO  '           / recorder number from antenna
TFORM5  = '1J      '           /
TTYPE6  = 'PBD_NO  '           / correlator playback drive
TFORM6  = '1J      '           /
TTYPE7  = 'SPEED   '           / tape speed and direction
TFORM7  = '1D      '           /
TTYPE8  = 'HEAD_POS'           / recorder headstack position
TFORM8  = '1J      '           /
TTYPE9  = 'QUALIFIER'          / 0 = statistics, 1 = out of sync, 2 = idle
TFORM9  = '1J      '           /
TTYPE10 = 'HEAD_NO '           / recorder head number
TFORM10 = '1J      '           /
TTYPE11 = 'PARITY  '           / parity error count
TFORM11 = '1J      '           /
TTYPE12 = 'HEADER  '           / header error count
TFORM12 = '1J      '           /
TTYPE13 = 'RESYNC  '           / resync count
TFORM13 = '1J      '           /
TTYPE14 = 'INVALID '           / invalid frame count
TFORM14 = '1J      '           /
TTYPE15 = 'FRAME   '           / frame count for above
TFORM15 = '1J      '           /
OBSCODE = 'BL146   '           /
RDATE   = '2007-08-23'         /
NO_STKD =                    4 /
STK_1   =                   -1 /
NO_BAND =                    4 /
NO_CHAN =                    8 /
REF_FREQ=   8.40549000000000000E+09 /
CHAN_BW =   1.00000000000000000E+06 /
REF_PIXL=   5.31250000000000000E-01 /
TABREV  =                    2 /
FILE_MJD=   5.43439079631558634E+04 /
END