XTENSION= 'BINTABLE'           / FITS Binary Table Extension
BITPIX  =                    8 /
NAXIS   =                    2 /
NAXIS1  =                   36 /
NAXIS2  =                   70 /
PCOUNT  =                    0 /
GCOUNT  =                    1 /
TFIELDS =                   10 /
EXTNAME = 'WEATHER '           /
EXTVER  =                    1 /
TTYPE1  = 'TIME    '           / time of measurement
TFORM1  = '1D      '           /
TUNIT1  = 'DAYS    '           /
TTYPE2  = 'TIME_INTERVAL'      / time span over which data applies
TFORM2  = '1E      '           /
TUNIT2  = 'DAYS    '           /
TTYPE3  = 'ANTENNA_NO'         / antenna id from antennas tbl
TFORM3  = '1J      '           /
TTYPE4  = 'TEMPERATURE'        / ambient temperature
TFORM4  = '1E      '           /
TUNIT4  = 'CENTIGRADE'         /
TTYPE5  = 'PRESSURE'           / atmospheric pressure
TFORM5  = '1E      '           /
TUNIT5  = 'MILLIBARS'          /
TTYPE6  = 'DEWPOINT'           / dewpoint
TFORM6  = '1E      '           /
TUNIT6  = 'CENTIGRADE'         /
TTYPE7  = 'WIND_VELOCITY'      / wind velocity
TFORM7  = '1E      '           /
TUNIT7  = 'M/SEC   '           /
TTYPE8  = 'WIND_DIRECTION'     / wind direction
TFORM8  = '1E      '           /
TUNIT8  = 'DEGREES '           /
TTYPE9  = 'WVR_H2O '           /
TFORM9  = '0E      '           /
TUNIT9  = '        '           /
TTYPE10 = 'IONOS_ELECTRON'     /
TFORM10 = '0E      '           /
TUNIT10 = '        '           /
OBSCODE = 'BL146   '           / Proposal code
RDATE   = '2007-08-23'         / Reference date
NO_STKD =                    4 / Nmbr stokes
STK_1   =                   -1 / First stokes
NO_BAND =                    4 / Number of basebands
NO_CHAN =                    8 / Number of channels
REF_FREQ=   8.40549000000000000E+09 / Frequency reference
CHAN_BW =   1.00000000000000000E+06 / Channel bandwidth
REF_PIXL=   5.31250000000000000E-01 /
TABREV  =                    1 /
MAPFUNC = '        '           /
WVR_TYPE= '        '           /
ION_TYPE= '        '           /
END